datamodule:
  video_dir: E:/chalearn_first_impression_dataset/frames/
  audio_dir: E:/chalearn_first_impression_dataset/pyaudiofeatures_30/
  text_dir: E:/chalearn_first_impression_dataset/scripts/bert_embeddings/
  label_dir:
    train: E:/chalearn_first_impression_dataset/annotation/original/annotation_training.csv
    valid: E:/chalearn_first_impression_dataset/annotation/original/annotation_validation.csv
    test: E:/chalearn_first_impression_dataset/annotation/original/annotation_test.csv
  target_list: 
    - openness
    - conscientiousness
    - extraversion
    - agreeableness
    - neuroticism
    - interview
  frame_count: 30
  seed: 0
  num_workers: 0
  batch_size: 32

module:
  encoder:
    video_channels:
      - [3, 8]
      - [8, 16]
      - [16, 32]
      - [32, 64]
      - [64, 128]
    video_input_size: 1152
    video_hidden_size: 512
    video_num_layers: 2
    audio_input_size: 68
    audio_hidden_size: 32
    audio_num_layers: 2
  regressor:
    fusion_hidden_size: 256
    num_class: 6
  classifier:
    fusion_hidden_size: 256
    num_class: 2